// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	models "github.com/paulocvasco/mercado-frescos-time-7/go-web/internal/models"
	repository "github.com/paulocvasco/mercado-frescos-time-7/go-web/internal/purchaseOrders/repository"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMysql is an autogenerated mock type for the RepositoryMysql type
type RepositoryMysql struct {
	mock.Mock
}

// Create provides a mock function with given fields: data
func (_m *RepositoryMysql) Create(data models.PurchaseOrders) (repository.ResultPost, error) {
	ret := _m.Called(data)

	var r0 repository.ResultPost
	if rf, ok := ret.Get(0).(func(models.PurchaseOrders) repository.ResultPost); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(repository.ResultPost)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.PurchaseOrders) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPurchaseOrder provides a mock function with given fields:
func (_m *RepositoryMysql) GetAllPurchaseOrder() ([]models.ResponsePurchaseByBuyer, error) {
	ret := _m.Called()

	var r0 []models.ResponsePurchaseByBuyer
	if rf, ok := ret.Get(0).(func() []models.ResponsePurchaseByBuyer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResponsePurchaseByBuyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIdPurchaseOrder provides a mock function with given fields: id
func (_m *RepositoryMysql) GetIdPurchaseOrder(id int) ([]models.ResponsePurchaseByBuyer, error) {
	ret := _m.Called(id)

	var r0 []models.ResponsePurchaseByBuyer
	if rf, ok := ret.Get(0).(func(int) []models.ResponsePurchaseByBuyer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResponsePurchaseByBuyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepositoryMysql interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryMysql creates a new instance of RepositoryMysql. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryMysql(t mockConstructorTestingTNewRepositoryMysql) *RepositoryMysql {
	mock := &RepositoryMysql{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
