// Code generated by mockery v2.13.1. DO NOT EDIT.

package mock

import (
	models "github.com/paulocvasco/mercado-frescos-time-7/go-web/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *Service) Create(_a0 models.PostWarehouse) (models.Warehouse, error) {
	ret := _m.Called(_a0)

	var r0 models.Warehouse
	if rf, ok := ret.Get(0).(func(models.PostWarehouse) models.Warehouse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.PostWarehouse) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0
func (_m *Service) Delete(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() (models.Warehouses, error) {
	ret := _m.Called()

	var r0 models.Warehouses
	if rf, ok := ret.Get(0).(func() models.Warehouses); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Warehouses)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: _a0
func (_m *Service) GetByID(_a0 int) (models.Warehouse, error) {
	ret := _m.Called(_a0)

	var r0 models.Warehouse
	if rf, ok := ret.Get(0).(func(int) models.Warehouse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *Service) Update(_a0 int, _a1 []byte) (models.Warehouse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 models.Warehouse
	if rf, ok := ret.Get(0).(func(int, []byte) models.Warehouse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.Warehouse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, []byte) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
