// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	repository "mercado-frescos-time-7/go-web/internal/inbound_orders/repository"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: order_date, order_number, employee_id, product_batch_id, warehouse_id
func (_m *Repository) Create(order_date string, order_number string, employee_id int, product_batch_id int, warehouse_id int) (repository.InboundOrders, error) {
	ret := _m.Called(order_date, order_number, employee_id, product_batch_id, warehouse_id)

	var r0 repository.InboundOrders
	if rf, ok := ret.Get(0).(func(string, string, int, int, int) repository.InboundOrders); ok {
		r0 = rf(order_date, order_number, employee_id, product_batch_id, warehouse_id)
	} else {
		r0 = ret.Get(0).(repository.InboundOrders)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int, int, int) error); ok {
		r1 = rf(order_date, order_number, employee_id, product_batch_id, warehouse_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
